In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("./Dataset/train.csv")
print(df.dtypes)
df.head()

id                                     int64
Age                                    int64
Flight Distance                        int64
Inflight wifi service                  int64
Departure/Arrival time convenient      int64
Ease of Online booking                 int64
Gate location                          int64
Food and drink                         int64
Online boarding                        int64
Seat comfort                           int64
Inflight entertainment                 int64
On-board service                       int64
Leg room service                       int64
Baggage handling                       int64
Checkin service                        int64
Cleanliness                            int64
Departure Delay in Minutes             int64
Arrival Delay in Minutes             float64
Gender                                   str
Customer Type                            str
Type of Travel                           str
Class                                    str
satisfaction                            bool
dtype: object

,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,...,Baggage handling,Checkin service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender,Customer Type,Type of Travel,Class,satisfaction
0,0,36,694,4,4,4,3,1,4,1,...,4,3,1,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
1,1,56,651,5,5,5,5,5,4,4,...,5,4,3,0,0.0,Male,Loyal Customer,Business travel,Business,True
2,2,31,1371,3,4,2,5,3,3,3,...,4,5,3,0,0.0,Female,Loyal Customer,Personal Travel,Eco,False
3,3,10,1616,3,5,3,3,3,3,3,...,3,4,3,0,0.0,Male,Loyal Customer,Personal Travel,Eco,False
4,4,23,481,3,4,3,4,5,3,5,...,5,3,5,5,0.0,Female,disloyal Customer,Business travel,Eco,False

In [ ]:
# Numerische Features
## Age                                    int64
## Flight Distance                        int64
## Inflight wifi service                  int64
## Departure/Arrival time convenient      int64
## Ease of Online booking                 int64
## Gate location                          int64
## Food and drink                         int64
## Online boarding                        int64
## Seat comfort                           int64
## Inflight entertainment                 int64
## On-board service                       int64
## Leg room service                       int64
## Baggage handling                       int64
## Checkin service                        int64
## Cleanliness                            int64
## Departure Delay in Minutes             int64
## Arrival Delay in Minutes


# Kategorische Features
## Gender                               
## Customer Type                           
## Type of Travel                          
## Class                                   
                            

# Target
## satisfaction

In [4]:
# Normalisierung bei Logistic Regression, Neural Network, SVM, KNN
# keine Normalisierung bei Tree-Modellen: Random Forest, XGBoost, LightGBM, CatBoost

# Label Encoding nicht pauschal verwenden:
# künstlich die Beziehung ordinal beschreiben
# Darum One-Hot Encoding besser
# Außer bei CatBoost (kann kategorische Features direkt verarbeiten)

In [ ]:
# Stratified Cross Validation
#

In [7]:
df.isna().sum()

id                             0
Age                            0
Annual_Income_USD              0
Daily_Commute_km               0
Number_of_Cars_Owned           0
Charging_Stations_Near_Home    0
Charging_Stations_Near_Work    0
Environmental_Concern_Level    0
Gender                         0
City_Type                      0
Current_Car_Type               0
Home_Charging_Possible         0
Subsidy_Available              0
Range_Anxiety_Level            0
Will_Buy_EV                    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df

In [11]:
df.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [14]:
numeric_features = [
    "Age",
    "Annual_Income_USD",
    "Daily_Commute_km",
    "Number_of_Cars_Owned",
    "Charging_Stations_Near_Home",
    "Charging_Stations_Near_Work",
    "Environmental_Concern_Level"
]

categorical_features = [
    "Gender",
    "City_Type",
    "Current_Car_Type"
]

binary_features = [
    "Home_Charging_Possible",
    "Subsidy_Available"
]

for col in categorical_features:
    print(col)
    print(df[col].value_counts())

df[numeric_features].describe().T
df["Will_Buy_EV"].value_counts(normalize=True)

Gender
Gender
Male      367954
Female    295427
Other       5284
Name: count, dtype: int64
City_Type
City_Type
Urban       289305
Suburban    255377
Rural       123983
Name: count, dtype: int64
Current_Car_Type
Current_Car_Type
Sedan        303459
SUV          246545
Hatchback     79438
Truck         39223
Name: count, dtype: int64

Will_Buy_EV
No     0.825355
Yes    0.174645
Name: proportion, dtype: float64

In [15]:
for col in categorical_features:
    print(
        df.groupby(col)["Will_Buy_EV"]
        .value_counts(normalize=True)
        .unstack()
    )

Will_Buy_EV        No       Yes
Gender
Female       0.822359  0.177641
Male         0.827747  0.172253
Other        0.826268  0.173732
Will_Buy_EV        No       Yes
City_Type
Rural        0.806611  0.193389
Suburban     0.819064  0.180936
Urban        0.838942  0.161058
Will_Buy_EV             No       Yes
Current_Car_Type
Hatchback         0.825701  0.174299
SUV               0.819047  0.180953
Sedan             0.828033  0.171967
Truck             0.843587  0.156413